
# 热部署
spring.thymeleaf.cache=false

# 修改Thymeleaf的编码
spring.thymeleaf.encoding=UTF-8

# 使用Html5
spring.thymeleaf.mode=HTML5

# 链接数据库
spring.datasource.url=jdbc:mysql://::1:3306/styletrans?serverTimezone=UTC&charactorEncoding=utf-8

# 用户名密码
spring.datasource.username=root
spring.datasource.password=aabbcc

# 链接数据库的驱动
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 图片上传大小限制
# 设置单个文件大小
spring.servlet.multipart.max-file-size= 50MB
# 设置单次请求文件的总大小
spring.servlet.multipart.max-request-size= 50MB

# 配置资源路径
imagelocation = C:/Deeplearning/learn/style_trans/image

spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static,file:${imagelocation}

# 开启驼峰映射
mybatis.configuration.map-underscore-to-camel-case=true

#邮件协议
spring.mail.protocol=smtp

#网易邮箱smtp服务器地址
spring.mail.host=smtp.163.com

#端口号
spring.mail.port=25

#发件人邮箱地址
spring.mail.username=gloomy9907@163.com

#授权码
spring.mail.password=DMVHQIXPCAZNWHHQ

#编码字符集
spring.mail.default-encoding=UTF-8

#开启debug模式以后会完整打印邮件发送过程的日志
spring.mail.properties.debug=true

# 开启文件上传和下载
spring.servlet.multipart.enabled=true

#自定义的上传文件存放路径
file.upload.dir=F:/MyJava/styletransfer/src/main/resources/static/file

#自定义禁止上传的文件类型
file.upload.disableType=dll,exe

spring.mvc.static.path-pattern=/**




